#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""
Offline profiler for TightLLM ILP planner.

Profiles three quantities required by the TightLLM KV distributor:
  1. MFU_attn(seq_len) — Attention layer Model FLOPs Utilization curve
  2. MFU_ffn(seq_len)  — FFN layer MFU curve
  3. PCIe H2D bandwidth — Effective bandwidth for KV block transfers
  4. GPU peak FLOPS     — From device properties / benchmark

Reference: TightLLM (Hu et al., IEEE TC 2025), Section IV-B, Eq 3-5.

Usage:
    python -m vllm.v1.profiling.tightllm_offline_profiler \
        --model /path/to/opt-2.7b \
        --output tightllm_profile.json \
        --seq-lengths 128 256 512 1024 2048 4096 8192
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

from vllm.logger import init_logger

logger = init_logger(__name__)


# ---------------------------------------------------------------------------
# Profile data container
# ---------------------------------------------------------------------------


@dataclass
class TightLLMProfileData:
    """Offline profiled data for TightLLM ILP planner.

    Stores MFU look-up tables (keyed by effective sequence length),
    effective PCIe bandwidth, GPU peak FLOPS, and model architecture
    parameters needed for the analytical FLOPS model.
    """

    # MFU look-up tables: {effective_seq_len: mfu_ratio}
    mfu_attn_by_seqlen: dict[int, float] = field(default_factory=dict)
    mfu_ffn_by_seqlen: dict[int, float] = field(default_factory=dict)

    # PCIe H2D effective bandwidth (bytes/s)
    pcie_bandwidth_h2d: float = 0.0

    # GPU peak FLOPS (FP16/BF16 tensor-core throughput)
    gpu_peak_flops: float = 0.0

    # Model architecture constants
    hidden_size: int = 0
    num_attention_heads: int = 0
    num_kv_heads: int = 0
    head_dim: int = 0
    ffn_dim: int = 0  # intermediate_size / ffn_dim
    num_layers: int = 0
    dtype_bytes: int = 2  # FP16 / BF16
    model_type: str = "opt"

    # Architecture-aware analytical FLOP coefficients. Projection terms are:
    #
    #   attention QKV: coefficient * tokens * hidden_size**2
    #   attention out: coefficient * tokens * hidden_size**2
    #   MLP:           coefficient * tokens * hidden_size * ffn_dim
    #
    # Constructor defaults describe profiles generated by the current
    # profiler. ``load`` supplies the historical attention-score coefficient
    # (2) when reading legacy JSON that predates score·V accounting.
    attention_qkv_flops_coefficient: float = 6.0
    attention_output_flops_coefficient: float = 2.0
    attention_score_flops_coefficient: float = 4.0
    mlp_flops_coefficient: float = 4.0

    # Interpolation arrays (built from the dicts above)
    _mfu_attn_seqlens: np.ndarray = field(
        init=False, repr=False, default_factory=lambda: np.array([1.0])
    )
    _mfu_attn_values: np.ndarray = field(
        init=False, repr=False, default_factory=lambda: np.array([0.5])
    )
    _mfu_ffn_seqlens: np.ndarray = field(
        init=False, repr=False, default_factory=lambda: np.array([1.0])
    )
    _mfu_ffn_values: np.ndarray = field(
        init=False, repr=False, default_factory=lambda: np.array([0.5])
    )

    def __post_init__(self) -> None:
        self._build_interpolation_tables()

    def _build_interpolation_tables(self) -> None:
        for attr_dict, attr_sl, attr_val in (
            ("mfu_attn_by_seqlen", "_mfu_attn_seqlens", "_mfu_attn_values"),
            ("mfu_ffn_by_seqlen", "_mfu_ffn_seqlens", "_mfu_ffn_values"),
        ):
            d = getattr(self, attr_dict)
            if d:
                seqlens = sorted(d.keys())
                setattr(self, attr_sl, np.array(seqlens, dtype=np.float64))
                setattr(
                    self,
                    attr_val,
                    np.array([d[s] for s in seqlens], dtype=np.float64),
                )

    def lookup_mfu_attn(self, effective_seqlen: int) -> float:
        """Linearly interpolate MFU_attn for *effective_seqlen*."""
        return float(
            np.interp(effective_seqlen, self._mfu_attn_seqlens, self._mfu_attn_values)
        )

    def lookup_mfu_ffn(self, effective_seqlen: int) -> float:
        """Linearly interpolate MFU_ffn for *effective_seqlen*."""
        return float(
            np.interp(effective_seqlen, self._mfu_ffn_seqlens, self._mfu_ffn_values)
        )

    # ---- Serialisation ----

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "mfu_attn_by_seqlen": {
                str(k): v for k, v in self.mfu_attn_by_seqlen.items()
            },
            "mfu_ffn_by_seqlen": {str(k): v for k, v in self.mfu_ffn_by_seqlen.items()},
            "pcie_bandwidth_h2d": self.pcie_bandwidth_h2d,
            "gpu_peak_flops": self.gpu_peak_flops,
            "hidden_size": self.hidden_size,
            "num_attention_heads": self.num_attention_heads,
            "num_kv_heads": self.num_kv_heads,
            "head_dim": self.head_dim,
            "ffn_dim": self.ffn_dim,
            "num_layers": self.num_layers,
            "dtype_bytes": self.dtype_bytes,
            "model_type": self.model_type,
            "attention_qkv_flops_coefficient": (
                self.attention_qkv_flops_coefficient
            ),
            "attention_output_flops_coefficient": (
                self.attention_output_flops_coefficient
            ),
            "attention_score_flops_coefficient": (
                self.attention_score_flops_coefficient
            ),
            "mlp_flops_coefficient": self.mlp_flops_coefficient,
        }
        with open(path, "w") as f:
            json.dump(data, f, indent=2)
        logger.info("TightLLM profile saved → %s", path)

    @classmethod
    def load(cls, path: str | Path) -> TightLLMProfileData:
        with open(path) as f:
            data = json.load(f)
        return cls(
            mfu_attn_by_seqlen={
                int(k): v for k, v in data["mfu_attn_by_seqlen"].items()
            },
            mfu_ffn_by_seqlen={int(k): v for k, v in data["mfu_ffn_by_seqlen"].items()},
            pcie_bandwidth_h2d=data["pcie_bandwidth_h2d"],
            gpu_peak_flops=data["gpu_peak_flops"],
            hidden_size=data["hidden_size"],
            num_attention_heads=data["num_attention_heads"],
            num_kv_heads=data.get("num_kv_heads", data["num_attention_heads"]),
            head_dim=data["head_dim"],
            ffn_dim=data["ffn_dim"],
            num_layers=data["num_layers"],
            dtype_bytes=data.get("dtype_bytes", 2),
            model_type=data.get("model_type", "opt"),
            attention_qkv_flops_coefficient=data.get(
                "attention_qkv_flops_coefficient", 6.0
            ),
            attention_output_flops_coefficient=data.get(
                "attention_output_flops_coefficient", 2.0
            ),
            # Preserve the historical planner formula for legacy profiles.
            # Newly generated profiles count both QK^T and score·V.
            attention_score_flops_coefficient=data.get(
                "attention_score_flops_coefficient", 2.0
            ),
            mlp_flops_coefficient=data.get("mlp_flops_coefficient", 4.0),
        )


@dataclass(frozen=True)
class TightLLMModelProfileSpec:
    """Normalized model architecture used by the microbenchmarks."""

    model_type: str
    hidden_size: int
    num_attention_heads: int
    num_kv_heads: int
    head_dim: int
    ffn_dim: int
    num_layers: int
    norm_eps: float
    attention_qkv_flops_coefficient: float
    attention_output_flops_coefficient: float
    attention_score_flops_coefficient: float
    mlp_flops_coefficient: float

    @property
    def uses_rms_norm(self) -> bool:
        return self.model_type == "llama"

    @property
    def uses_swiglu(self) -> bool:
        return self.model_type == "llama"


def resolve_model_profile_spec(config) -> TightLLMModelProfileSpec:
    """Resolve supported HuggingFace configs without changing the JSON schema.

    OPT keeps the legacy MHA + ReLU/two-projection benchmark. Llama uses
    RMSNorm, its configured MHA/GQA projection widths, and SwiGLU's
    gate/up/down projections.
    """

    model_type = str(getattr(config, "model_type", "")).lower()
    if model_type not in {"llama", "opt"}:
        raise ValueError(
            "TightLLM offline profiling currently supports only OPT and Llama; "
            f"got model_type={model_type!r}."
        )

    hidden_size = int(config.hidden_size)
    num_attention_heads = int(config.num_attention_heads)
    num_kv_heads = int(
        getattr(config, "num_key_value_heads", None) or num_attention_heads
    )
    head_dim = int(
        getattr(config, "head_dim", None)
        or hidden_size // num_attention_heads
    )
    num_layers = int(config.num_hidden_layers)

    if hidden_size <= 0 or num_attention_heads <= 0 or num_kv_heads <= 0:
        raise ValueError("Model hidden size and attention head counts must be > 0.")
    if head_dim <= 0 or num_attention_heads * head_dim != hidden_size:
        raise ValueError(
            "TightLLM profiling requires num_attention_heads * head_dim "
            f"to equal hidden_size; got {num_attention_heads} * {head_dim} "
            f"!= {hidden_size}."
        )
    if num_attention_heads % num_kv_heads != 0:
        raise ValueError(
            "num_attention_heads must be divisible by num_key_value_heads; "
            f"got {num_attention_heads} and {num_kv_heads}."
        )

    if model_type == "llama":
        ffn_dim = int(config.intermediate_size)
        hidden_act = str(getattr(config, "hidden_act", "silu")).lower()
        if hidden_act != "silu":
            raise ValueError(
                "Llama TightLLM profiling currently requires hidden_act='silu'; "
                f"got {hidden_act!r}."
            )
        norm_eps = float(getattr(config, "rms_norm_eps", 1e-6))
        mlp_flops_coefficient = 6.0
    else:
        ffn_dim = int(
            getattr(config, "ffn_dim", None)
            or getattr(config, "intermediate_size", 4 * hidden_size)
        )
        norm_eps = float(getattr(config, "layer_norm_eps", 1e-5))
        mlp_flops_coefficient = 4.0

    if ffn_dim <= 0 or num_layers <= 0 or norm_eps <= 0:
        raise ValueError("Model FFN size, layer count, and norm epsilon must be > 0.")

    kv_ratio = num_kv_heads / num_attention_heads
    # Q costs 2*H^2 FLOPs/token; K and V together cost
    # 4*H^2*(num_kv_heads/num_attention_heads). Standard output projection
    # costs another 2*H^2.
    attention_qkv_flops_coefficient = 2.0 + 4.0 * kv_ratio

    return TightLLMModelProfileSpec(
        model_type=model_type,
        hidden_size=hidden_size,
        num_attention_heads=num_attention_heads,
        num_kv_heads=num_kv_heads,
        head_dim=head_dim,
        ffn_dim=ffn_dim,
        num_layers=num_layers,
        norm_eps=norm_eps,
        attention_qkv_flops_coefficient=attention_qkv_flops_coefficient,
        attention_output_flops_coefficient=2.0,
        attention_score_flops_coefficient=4.0,
        mlp_flops_coefficient=mlp_flops_coefficient,
    )


# ---------------------------------------------------------------------------
# Profiling helpers
# ---------------------------------------------------------------------------


def profile_gpu_peak_flops(
    device: torch.device,
    dtype: torch.dtype = torch.float16,
) -> float:
    """Benchmark GPU peak FLOPS by scanning several matmul shapes.

    A single fixed shape (e.g. 4096³) frequently underestimates peak —
    cuBLAS picks different kernels for different shapes, and some
    workload-relevant shapes (rectangular FFN GEMMs, FP16-accumulate
    paths used by FlashAttention) routinely beat a square 4096³
    measurement.  We scan several square + rectangular shapes and
    return the maximum achieved FLOPS.
    """
    shapes: list[tuple[int, int, int]] = [
        (2048, 2048, 2048),
        (4096, 4096, 4096),
        (8192, 8192, 8192),
        (4096, 8192, 4096),
        (8192, 4096, 8192),
        (2048, 8192, 2048),
    ]

    best = 0.0
    for M, N, K in shapes:
        try:
            a = torch.randn(M, K, device=device, dtype=dtype)
            b = torch.randn(K, N, device=device, dtype=dtype)

            for _ in range(10):
                torch.mm(a, b)
            torch.cuda.synchronize()

            iters = 50
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            for _ in range(iters):
                torch.mm(a, b)
            end.record()
            torch.cuda.synchronize()

            elapsed_s = start.elapsed_time(end) / 1000.0
            flops = 2 * M * N * K * iters / elapsed_s
            if flops > best:
                best = flops

            del a, b
            torch.cuda.empty_cache()
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            continue

    return best


def profile_pcie_bandwidth(
    device: torch.device,
    block_size: int = 16,
    num_kv_heads: int = 32,
    head_dim: int = 80,
    dtype: torch.dtype = torch.float16,
    num_blocks_list: list[int] | None = None,
) -> float:
    """Profile effective PCIe H2D bandwidth via pinned-memory copies."""
    if num_blocks_list is None:
        num_blocks_list = [16, 32, 64, 128, 256, 512]

    dtype_bytes = torch.tensor([], dtype=dtype).element_size()
    bandwidths: list[float] = []

    for num_blocks in num_blocks_list:
        total_elements = num_blocks * block_size * 2 * num_kv_heads * head_dim
        total_bytes = total_elements * dtype_bytes

        cpu_tensor = torch.randn(total_elements, dtype=dtype).pin_memory()
        gpu_tensor = torch.empty(total_elements, device=device, dtype=dtype)

        # Warmup
        for _ in range(5):
            gpu_tensor.copy_(cpu_tensor, non_blocking=True)
            torch.cuda.synchronize()

        iters = 20
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)
        start.record()
        for _ in range(iters):
            gpu_tensor.copy_(cpu_tensor, non_blocking=True)
        end.record()
        torch.cuda.synchronize()

        elapsed_s = start.elapsed_time(end) / 1000.0
        bw = (total_bytes * iters) / elapsed_s
        bandwidths.append(bw)

    # Return median bandwidth
    return float(sorted(bandwidths)[len(bandwidths) // 2])


def _run_attention_microbenchmark(
    x: torch.Tensor,
    w_qkv: torch.Tensor,
    w_out: torch.Tensor,
    *,
    model_type: str,
    num_heads: int,
    num_kv_heads: int,
    head_dim: int,
    norm_weight: torch.Tensor | None = None,
    norm_eps: float = 1e-5,
) -> torch.Tensor:
    """Execute one architecture-faithful attention microbenchmark."""

    if model_type == "llama":
        if norm_weight is None:
            raise ValueError("Llama attention profiling requires RMSNorm weights.")
        x = F.rms_norm(x, (x.shape[-1],), norm_weight, norm_eps)
    elif model_type != "opt":
        raise ValueError(f"Unsupported model_type={model_type!r}.")

    batch_size, seq_len, _ = x.shape
    q_size = num_heads * head_dim
    kv_size = num_kv_heads * head_dim
    qkv = torch.matmul(x, w_qkv)
    q_part, k_part, v_part = qkv.split([q_size, kv_size, kv_size], dim=-1)
    q = q_part.view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)
    k = k_part.view(batch_size, seq_len, num_kv_heads, head_dim).transpose(1, 2)
    v = v_part.view(batch_size, seq_len, num_kv_heads, head_dim).transpose(1, 2)

    # Full L² attention (no causal mask) keeps executed work consistent with
    # the FLOP formula used for the MFU denominator.
    attn_out = F.scaled_dot_product_attention(
        q,
        k,
        v,
        enable_gqa=num_kv_heads != num_heads,
    )
    attn_out = (
        attn_out.transpose(1, 2)
        .contiguous()
        .view(batch_size, seq_len, q_size)
    )
    return torch.matmul(attn_out, w_out)


def _run_mlp_microbenchmark(
    x: torch.Tensor,
    w_in: torch.Tensor,
    w_out: torch.Tensor,
    *,
    model_type: str,
    norm_weight: torch.Tensor | None = None,
    norm_eps: float = 1e-5,
) -> torch.Tensor:
    """Execute one OPT-ReLU or Llama-RMSNorm/SwiGLU MLP benchmark."""

    if model_type == "llama":
        if norm_weight is None:
            raise ValueError("Llama MLP profiling requires RMSNorm weights.")
        x = F.rms_norm(x, (x.shape[-1],), norm_weight, norm_eps)
        gate, up = torch.matmul(x, w_in).chunk(2, dim=-1)
        hidden = F.silu(gate) * up
    elif model_type == "opt":
        hidden = F.relu(torch.matmul(x, w_in))
    else:
        raise ValueError(f"Unsupported model_type={model_type!r}.")
    return torch.matmul(hidden, w_out)


def attention_flops_per_forward(
    *,
    seq_len: int,
    hidden_size: int,
    num_heads: int,
    head_dim: int,
    qkv_flops_coefficient: float,
    output_flops_coefficient: float,
    score_flops_coefficient: float = 4.0,
) -> float:
    """Model FLOPs for the profiled prefill attention forward."""

    projection_flops = (
        (qkv_flops_coefficient + output_flops_coefficient)
        * seq_len
        * hidden_size
        * hidden_size
    )
    score_flops = (
        score_flops_coefficient
        * num_heads
        * seq_len
        * seq_len
        * head_dim
    )
    return projection_flops + score_flops


def mlp_flops_per_forward(
    *,
    seq_len: int,
    hidden_size: int,
    ffn_dim: int,
    mlp_flops_coefficient: float,
) -> float:
    """Model FLOPs for the profiled OPT or Llama MLP forward."""

    return mlp_flops_coefficient * seq_len * hidden_size * ffn_dim


def profile_mfu_attn(
    device: torch.device,
    hidden_size: int,
    num_heads: int,
    head_dim: int,
    peak_flops: float,
    seq_lengths: list[int],
    dtype: torch.dtype = torch.float16,
    *,
    num_kv_heads: int | None = None,
    model_type: str = "opt",
    norm_eps: float = 1e-5,
    qkv_flops_coefficient: float | None = None,
    output_flops_coefficient: float = 2.0,
    score_flops_coefficient: float = 4.0,
) -> dict[int, float]:
    """Profile attention MFU at discrete sequence lengths.

    Matches TightLLM (Hu et al., IEEE TC 2025) §IV-B / Fig. 7: the curve
    is measured by running a *prefill* self-attention pass of length L
    (q.len = kv.len = L) and dividing the theoretical FLOPs by wall time.

    The default path is the legacy OPT MHA benchmark. The Llama path adds
    RMSNorm and uses configured Q/K/V widths (MHA for Llama-2-7B, GQA for
    variants with fewer KV heads).
    """
    if num_kv_heads is None:
        num_kv_heads = num_heads
    if num_heads % num_kv_heads != 0:
        raise ValueError("num_heads must be divisible by num_kv_heads")
    if model_type not in {"llama", "opt"}:
        raise ValueError(f"Unsupported model_type={model_type!r}.")
    if qkv_flops_coefficient is None:
        qkv_flops_coefficient = 2.0 + 4.0 * num_kv_heads / num_heads

    mfu_by_seqlen: dict[int, float] = {}

    for seq_len in seq_lengths:
        if seq_len <= 0:
            continue
        try:
            x = torch.randn(1, seq_len, hidden_size, device=device, dtype=dtype)
            q_size = num_heads * head_dim
            kv_size = num_kv_heads * head_dim
            w_qkv = torch.randn(
                hidden_size,
                q_size + 2 * kv_size,
                device=device,
                dtype=dtype,
            )
            w_out = torch.randn(q_size, hidden_size, device=device, dtype=dtype)
            norm_weight = (
                torch.ones(hidden_size, device=device, dtype=dtype)
                if model_type == "llama"
                else None
            )

            def _run():
                return _run_attention_microbenchmark(
                    x,
                    w_qkv,
                    w_out,
                    model_type=model_type,
                    num_heads=num_heads,
                    num_kv_heads=num_kv_heads,
                    head_dim=head_dim,
                    norm_weight=norm_weight,
                    norm_eps=norm_eps,
                )

            for _ in range(5):
                _run()
            torch.cuda.synchronize()

            iters = 50
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            for _ in range(iters):
                _run()
            end.record()
            torch.cuda.synchronize()

            elapsed_s = start.elapsed_time(end) / 1000.0

            flops_per = attention_flops_per_forward(
                seq_len=seq_len,
                hidden_size=hidden_size,
                num_heads=num_heads,
                head_dim=head_dim,
                qkv_flops_coefficient=qkv_flops_coefficient,
                output_flops_coefficient=output_flops_coefficient,
                score_flops_coefficient=score_flops_coefficient,
            )
            actual = flops_per * iters / elapsed_s
            mfu_by_seqlen[seq_len] = actual / peak_flops

            del x, w_qkv, w_out, norm_weight
            torch.cuda.empty_cache()

        except torch.cuda.OutOfMemoryError:
            logger.warning(
                "OOM at seq_len=%d during attention profiling, skipping.", seq_len
            )
            torch.cuda.empty_cache()
            break

    return mfu_by_seqlen


def profile_mfu_ffn(
    device: torch.device,
    hidden_size: int,
    ffn_dim: int,
    peak_flops: float,
    seq_lengths: list[int],
    dtype: torch.dtype = torch.float16,
    *,
    model_type: str = "opt",
    norm_eps: float = 1e-5,
    mlp_flops_coefficient: float | None = None,
) -> dict[int, float]:
    """Profile FFN MFU at discrete sequence lengths (prefill-style).

    The legacy OPT path executes ReLU with input/output projections. Llama
    executes RMSNorm and SwiGLU with logical gate/up/down projections; gate
    and up share one packed GEMM, matching vLLM's merged projection.
    """
    if model_type not in {"llama", "opt"}:
        raise ValueError(f"Unsupported model_type={model_type!r}.")
    if mlp_flops_coefficient is None:
        mlp_flops_coefficient = 6.0 if model_type == "llama" else 4.0

    mfu_by_seqlen: dict[int, float] = {}

    for seq_len in seq_lengths:
        if seq_len <= 0:
            continue
        try:
            x = torch.randn(1, seq_len, hidden_size, device=device, dtype=dtype)
            input_projection_size = (
                2 * ffn_dim if model_type == "llama" else ffn_dim
            )
            w_in = torch.randn(
                hidden_size,
                input_projection_size,
                device=device,
                dtype=dtype,
            )
            w_out = torch.randn(ffn_dim, hidden_size, device=device, dtype=dtype)
            norm_weight = (
                torch.ones(hidden_size, device=device, dtype=dtype)
                if model_type == "llama"
                else None
            )

            def _run():
                return _run_mlp_microbenchmark(
                    x,
                    w_in,
                    w_out,
                    model_type=model_type,
                    norm_weight=norm_weight,
                    norm_eps=norm_eps,
                )

            for _ in range(5):
                _run()
            torch.cuda.synchronize()

            iters = 50
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            for _ in range(iters):
                _run()
            end.record()
            torch.cuda.synchronize()

            elapsed_s = start.elapsed_time(end) / 1000.0
            flops_per = mlp_flops_per_forward(
                seq_len=seq_len,
                hidden_size=hidden_size,
                ffn_dim=ffn_dim,
                mlp_flops_coefficient=mlp_flops_coefficient,
            )
            actual = flops_per * iters / elapsed_s
            mfu_by_seqlen[seq_len] = actual / peak_flops

            del x, w_in, w_out, norm_weight
            torch.cuda.empty_cache()

        except torch.cuda.OutOfMemoryError:
            logger.warning(
                "OOM at seq_len=%d during FFN profiling, skipping.", seq_len
            )
            torch.cuda.empty_cache()
            break

    return mfu_by_seqlen


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def run_offline_profile(
    model_name_or_path: str,
    output_path: str,
    seq_lengths: list[int] | None = None,
    device: str = "cuda:0",
    block_size: int = 16,
) -> TightLLMProfileData:
    """Run complete offline profiling and save results.

    Args:
        model_name_or_path: HuggingFace model name or local path.
        output_path: Where to save the profile JSON.
        seq_lengths: Sequence lengths at which to measure MFU.
        device: CUDA device string.
        block_size: KV cache block size (for bandwidth profiling).

    Returns:
        The populated ``TightLLMProfileData``.
    """
    from transformers import AutoConfig

    if seq_lengths is None:
        seq_lengths = [128, 256, 512, 1024, 2048, 4096, 8192]

    config = AutoConfig.from_pretrained(model_name_or_path)
    spec = resolve_model_profile_spec(config)

    torch_device = torch.device(device)
    dtype = torch.float16

    print(f"Model : {model_name_or_path}")
    print(
        f"  type={spec.model_type}  H={spec.hidden_size}  "
        f"heads={spec.num_attention_heads}  kv_heads={spec.num_kv_heads}  "
        f"head_dim={spec.head_dim}  ffn_dim={spec.ffn_dim}  "
        f"layers={spec.num_layers}"
    )

    # 1. GPU peak FLOPS
    print("\n[1/4] GPU peak FLOPS ...")
    peak_flops = profile_gpu_peak_flops(torch_device, dtype)
    print(f"  {peak_flops:.2e}  ({peak_flops / 1e12:.1f} TFLOPS)")

    # 2. PCIe bandwidth
    print("\n[2/4] PCIe H2D bandwidth ...")
    bandwidth = profile_pcie_bandwidth(
        torch_device,
        block_size=block_size,
        num_kv_heads=spec.num_kv_heads,
        head_dim=spec.head_dim,
        dtype=dtype,
    )
    print(f"  {bandwidth:.2e} B/s  ({bandwidth / 1e9:.1f} GB/s)")

    # 3. Attention MFU
    print(f"\n[3/4] Attention MFU  seq_lengths={seq_lengths}")
    mfu_attn = profile_mfu_attn(
        torch_device,
        spec.hidden_size,
        spec.num_attention_heads,
        spec.head_dim,
        peak_flops,
        seq_lengths,
        dtype,
        num_kv_heads=spec.num_kv_heads,
        model_type=spec.model_type,
        norm_eps=spec.norm_eps,
        qkv_flops_coefficient=spec.attention_qkv_flops_coefficient,
        output_flops_coefficient=spec.attention_output_flops_coefficient,
        score_flops_coefficient=spec.attention_score_flops_coefficient,
    )
    for sl, val in sorted(mfu_attn.items()):
        print(f"  seq_len={sl:>6d}  MFU_attn={val:.4f}")

    # 4. FFN MFU
    print(f"\n[4/4] FFN MFU  seq_lengths={seq_lengths}")
    mfu_ffn = profile_mfu_ffn(
        torch_device,
        spec.hidden_size,
        spec.ffn_dim,
        peak_flops,
        seq_lengths,
        dtype,
        model_type=spec.model_type,
        norm_eps=spec.norm_eps,
        mlp_flops_coefficient=spec.mlp_flops_coefficient,
    )
    for sl, val in sorted(mfu_ffn.items()):
        print(f"  seq_len={sl:>6d}  MFU_ffn ={val:.4f}")

    profile_data = TightLLMProfileData(
        mfu_attn_by_seqlen=mfu_attn,
        mfu_ffn_by_seqlen=mfu_ffn,
        pcie_bandwidth_h2d=bandwidth,
        gpu_peak_flops=peak_flops,
        hidden_size=spec.hidden_size,
        num_attention_heads=spec.num_attention_heads,
        num_kv_heads=spec.num_kv_heads,
        head_dim=spec.head_dim,
        ffn_dim=spec.ffn_dim,
        num_layers=spec.num_layers,
        model_type=spec.model_type,
        attention_qkv_flops_coefficient=(
            spec.attention_qkv_flops_coefficient
        ),
        attention_output_flops_coefficient=(
            spec.attention_output_flops_coefficient
        ),
        attention_score_flops_coefficient=(
            spec.attention_score_flops_coefficient
        ),
        mlp_flops_coefficient=spec.mlp_flops_coefficient,
    )
    profile_data.save(output_path)
    return profile_data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="TightLLM offline profiler — collects MFU and bandwidth data"
    )
    parser.add_argument("--model", required=True, help="Model name or path")
    parser.add_argument("--output", required=True, help="Output JSON path")
    parser.add_argument(
        "--seq-lengths",
        type=int,
        nargs="+",
        default=[128, 256, 512, 1024, 2048, 4096, 8192],
        help="Sequence lengths to profile MFU at",
    )
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--device", default="cuda:0")
    args = parser.parse_args()

    run_offline_profile(
        model_name_or_path=args.model,
        output_path=args.output,
        seq_lengths=args.seq_lengths,
        device=args.device,
        block_size=args.block_size,
    )
